include $(GOROOT)/src/Make.$(GOARCH)

TARG=matrix
GOFILES=\
        matrix.go\
        arithmetic.go\
        error.go\
        util.go\
        dense.go\
        dense_arithmetic.go\
        dense_basic.go\
        dense_data.go\
        dense_decomp.go\
        dense_eigen.go\
        dense_svd.go\
        sparse.go\
        sparse_arithmetic.go\
        sparse_basic.go\
        pivot.go\
        pivot_arithmetic.go\
        pivot_basic.go\

include $(GOROOT)/src/Make.pkg
